# -*- coding: utf-8 -*-
"""DM assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ykYkekyn-we0Iu0rijXl_cEQmBS9t18
"""

import pandas as pd

"""import all dataset"""

test_ds = pd.read_csv('test.csv')
test_ds.info()
train_ds = pd.read_csv('train.csv')
train_ds.info()
gender_ds = pd.read_csv('gender_submission.csv');
gender_ds.info()

"""Add "survived" column in "test" dataset ( merging)"""

test_ds["Survived"] = gender_ds["Survived"]

test_ds.info()
train_ds.info()

"""Rearrange column of one dataset according to other"""

test_ds = test_ds[train_ds.columns]

"""concate both datasets (test,train) to new dataset"""

new_dataset = pd.concat([train_ds, test_ds], ignore_index=True)

"""check how many values are missing from each column"""

(new_dataset.isnull().sum())

new_dataset["Embarked"].unique()
new_dataset.dropna(subset=['Embarked'], inplace=True)
new_dataset

new_dataset['Age'].fillna(new_dataset['Age'].median(), inplace=True)
new_dataset

new_dataset.isnull().sum()

new_dataset['Fare'].unique()
new_dataset.dropna(subset=['Fare'], inplace=True)
new_dataset

new_dataset['HasCabin'] = new_dataset['Cabin'].notnull().astype(int)
new_dataset

new_dataset.drop(columns = 'Cabin', inplace=True)
new_dataset

"""Extracting last names of the persons"""

new_dataset['Last_Name'] = new_dataset['Name'].str.split(',').str[0]

new_dataset

"""Extracting title like Mr,Mrs"""

new_dataset['Title'] = new_dataset['Name'].str.split('.').str[0].str.split(',').str[1].str.strip()

"""extracting first name of single persons"""

names_of_singles = new_dataset[(new_dataset['Title'] != 'Mrs') | (new_dataset['Title'] != 'Mme')]['Name']
first_name = names_of_singles.str.split(".").str[1].str.strip()
new_dataset.loc[(new_dataset['Title'] != 'Mrs') | (new_dataset['Title'] != 'Mme'), 'First_Name'] = first_name

names_of_ML = new_dataset[(new_dataset['Title'] == 'Mrs') | (new_dataset['Title'] == 'Mme')]['Name']
first_name_of_ML = names_of_ML.str.split("(").str[1].str.rstrip(")").str.strip()
new_dataset.loc[(new_dataset['Title'] == 'Mrs') | (new_dataset['Title'] == 'Mme'), 'First_Name'] = first_name_of_ML

new_dataset.drop(columns=['Name'], inplace=True)

new_dataset.to_csv('new_cleaned_dataset.csv', index=False)

new_dataset['Ticket'] = new_dataset['Ticket'].str.replace('.','')

"""Filling 'Fare' column with median"""

new_dataset['Fare'].replace(0, new_dataset['Fare'].median(), inplace=True)

"""fare binning"""

new_dataset['Binned_Fare'] = pd.qcut(new_dataset['Fare'], 4, labels=['low', 'medium', 'high', 'very high'])

"""age binning"""

bins = [0, 2, 12, 19, 35, 50, 60, float('inf')]
labels = ['Infant', 'Child', 'Teenager', 'Young Adult', 'Adult', 'Middle Aged', 'Senior']
new_dataset['Binned_Age'] = pd.cut(new_dataset['Age'], bins=bins, labels=labels)

new_dataset = new_dataset[['PassengerId','Survived','Title','First_Name', 'Last_Name', 'Sex', 'Age','Binned_Age','SibSp','Parch','Ticket','Pclass','Embarked','HasCabin','Fare','Binned_Fare']]

"""Saving results into csv"""

new_dataset.to_csv('result.csv', index=False)